#in makefile, a hash indicates a comment instead
all: hellopi myhellopi printdatatypes calcdatatypes
hellopi: hellopi.c
	gcc -o hellopi hellopi.c
myhellopi: myhellopi.c
	gcc -o myhellopi myhellopi.c
printdatatypes: printdatatypes.c
	gcc -o printdatatypes printdatatypes.c
calcdatatypes: calcdatatypes.c
	gcc -o calcdatatypes calcdatatypes.c


