#!/usr/bin/sudo bash
# Set GPIO pin 8, low activating Arduino reset
sudo echo "8"   >/sys/class/gpio/export
sudo echo "out" >/sys/class/gpio/gpio8/direction
sudo echo "0"   >/sys/class/gpio/gpio8/value
sudo echo "8"   >/sys/class/gpio/unexport
