#!/usr/bin/python3
import serial
import time


serial_port = serial.Serial('/dev/serial0', 115200, timeout=1, writeTimeout=0)
# First read of A
serial_port.write('A'.encode())
dataA1 = serial_port.readline(6).decode()
#print('DataA1 = ',dataA1)
floatA1 = float(dataA1)
#print ('floatA1 = ',floatA1)
time.sleep(0.1)
# Second read of A
serial_port.write('A'.encode())
serial_port.flushInput()
dataA2 = serial_port.readline(6).decode()
#print('DataA2 = ',dataA2)
floatA2 = float(dataA2)
#print ('floatA2 = ',floatA2)
time.sleep(0.1)
# Third read of A
serial_port.write('A'.encode())
serial_port.flushInput()
dataA3 = serial_port.readline(6).decode()
#print('DataA3 = ',dataA3)
floatA3 = float(dataA3)
#print ('floatA3 = ',floatA3)
# Average the 3 reading of A1
#print ('Average = ', ((floatA1 + floatA2 + floatA3)/3))
AverageA1 = ((floatA1 + floatA2 + floatA3)/3)
#print ('AverageA1 = ', AverageA1)
AverageA1 = "{:.4f}".format(AverageA1)
print ('Average A = ', AverageA1)
time.sleep(0.1)
#serial_port = serial.Serial('/dev/serial0', 115200, timeout=1, writeTimeout=0)
# First read of B
serial_port.write('B'.encode())
serial_port.flushInput()
dataB1 = serial_port.readline(6).decode()
#print('DataB1 = ',dataB1)
floatB1 = float(dataB1)
#print ('floatB1 = ',floatB1)
time.sleep(0.1)
# Second read of B
serial_port.write('B'.encode())
serial_port.flushInput()
dataB2 = serial_port.readline(6).decode()
#print('DataB2 = ',dataB2)
floatB2 = float(dataB2)
#print ('floatB2 = ',floatB2)
time.sleep(0.1)
# Third read of B
serial_port.write('B'.encode())
serial_port.flushInput()
dataB3 = serial_port.readline(6).decode()
#print('DataB3 = ',dataB3)
floatB3 = float(dataB3)
#print ('floatB3 = ',floatB3)
# Average the 3 reading of B
#print ('Average = ', ((floatB1 + floatB2 + floatB3)/3))
AverageB1 = ((floatB1 + floatB2 + floatB3)/3)
#print ('AverageB1 = ', AverageB1)
AverageB1 = "{:.4f}".format(AverageB1)
print ('Average B = ', AverageB1)
time.sleep(0.1)
#serial_port = serial.Serial('/dev/serial0', 115200, timeout=1, writeTimeout=0)
# First read of C
serial_port.write('C'.encode())
serial_port.flushInput()
dataC1 = serial_port.readline(6).decode()
#print('DataC1 = ',dataC1)
floatC1 = float(dataC1)
#print ('floatC1 = ',floatC1)
time.sleep(0.1)
# Second read of C
serial_port.write('C'.encode())
serial_port.flushInput()
dataC2 = serial_port.readline(6).decode()
#print('DataC2 = ',dataC2)
floatC2 = float(dataC2)
#print ('floatC2 = ',floatC2)
time.sleep(0.1)
# Third read of C
serial_port.write('C'.encode())
serial_port.flushInput()
dataC3 = serial_port.readline(6).decode()
#print('DataC3 = ',dataC3)
floatC3 = float(dataC3)
#print ('floatC3 = ',floatC3)
# Average the 3 reading of C
#print ('Average = ', ((floatC1 + floatC2 + floatC3)/3))
AverageC1 = ((floatC1 + floatC2 + floatC3)/3)
#print ('AverageC1 = ', AverageC1)
AverageC1 = "{:.4f}".format(AverageC1)
print ('Average C = ', AverageC1)
time.sleep(0.1)
#time.sleep(0.1)
#print("Data from input C: ")
#serial_port.flushInput()
#serial_port.write('C'.encode())
#dataC = serial_port.readline(6).decode()
#print (dataC)
